name: my_components
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  heroicons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Nunito
      fonts:
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Black.ttf
          weight: 900
        - asset: lib/src/assets/fonts/NunitoSans_10pt-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/NunitoSans_10pt-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/src/assets/fonts/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: lib/src/assets/fonts/NunitoSans_10pt-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Italic.ttf
          style: italic
          weight: 400
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: lib/src/assets/fonts/NunitoSans_10pt-LightItalic.ttf
          style: italic
          weight: 300
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: lib/src/assets/fonts/NunitoSans_10pt-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: lib/src/assets/fonts/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: lib/src/assets/fonts/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: lib/src/assets/fonts/NunitoSans_10pt-SemiBoldItalic.ttf
          style: italic
          weight: 600