part of solfacil_ui_components;

const _mainThemeJson = {
  'colors': {
    'vibin': '#D8385E',
    'hope': '#1D856C',
    'energy': '#FFC24C',
    'relax': '#5340C9',
    'peace': '#FFB0A7',
    'brandingVerve': '#FF874C',
    'verve': '#CA4808',
    'uplift': '#FF4438',
    'deepPurple': '#710252',
    'yoga': '#FFEEF2',
    'success': '#C1EEDB',
    'neutral': '#E0DFFF',
    'attention': '#FCD6C3',
    'stamina': '#231B22',
    'deep': '#6B6B78',
    'medium': '#9898A6',
    'light': '#D7D7E0',
    'clear': '#F5F5FA',
    'white': '#FFFFFF',
    'primary': '#D8385E',
    'secondary': '#231B22',
    'feedback': {
      'success': {
        'light': '#C1EEDB',
        'dark': '#1D856C',
      },
      'informative': {
        'light': '#E0DFFF',
        'dark': '#5340C9',
      },
      'attention': {
        'light': '#FCD6C3',
        'dark': '#CA4808',
      },
      'neutral': {
        'light': '#D7D7E0',
        'dark': '#9898A6',
      },
    },
    'text': {
      'primary': '#231B22',
      'secondary': '#6B6B78',
      'disabled': '#D7D7E0',
    },
    'elements': {
      'selectionAndIcons': '#9898A6',
      'lineAndBorders': '#D7D7E0',
      'backgroundAndDisabled': '#F5F5FA',
    },
  },
  'fontWeights': {
    'light': 300,
    'regular': 400,
    'medium': 500,
    'bold': 700,
    'black': 900,
  },
  'fontSizes': {
    'xxsmall': 10,
    'xsmall': 12,
    'small': 14,
    'medium': 16,
    'large': 20,
    'xlarge': 24,
    'xxlarge': 32,
    'xxxlarge': 40,
    'huge': 48,
  },
  'borderRadius': {
    'sharp': 0,
    'xsmall': 4,
    'small': 8,
    'regular': 16,
    'circle': 9999,
  },
  'borderWidth': {
    'zero': 0,
    'small': 1,
    'medium': 2,
  },
  'spacings': {
    'zero': 0,
    'xxxsmall': 4,
    'xxsmall': 8,
    'xsmall': 12,
    'small': 16,
    'medium': 20,
    'large': 24,
    'xlarge': 32,
    'xxlarge': 40,
    'xxxlarge': 56,
    'huge': 72,
    'xhuge': 80,
  },
};
