name: Flutter Web to Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Configure git
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      
      - name: Build example
        run: |
          cd example/
          flutter config --enable-web
          flutter pub get
          flutter build web --release --base-href="/my-components/"

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: example/build/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
